"""
Orchestrator chain — decompose a complex query into per-source worker tasks.

Purpose
-------
On the ``deep_research`` path the agent does not retrieve directly from the user's
question. Instead, this chain breaks the question into a small list of focused
:class:`~agent.schemas.WorkerTask` objects (one per source-specialized worker). The
node layer (:mod:`agent.nodes.orchestrate`) then fans these tasks out via LangGraph's
``Send`` primitive; each task executes the same ``worker_node`` with a different
``WorkerType``.

Design choices
--------------
1. Strict :class:`~agent.schemas.OrchestrationPlan` schema (Pydantic) — no free text.
2. Bounded plan size: at most ``max_workers`` tasks (capped in the node, not the LLM).
3. ``task_id`` values are simple ``"t1"``, ``"t2"`` etc., generated by the LLM but
   re-keyed deterministically in the node (``_ensure_tasks``) for reproducibility.
4. If the LLM emits zero tasks, the orchestrate node falls back to a single
   ``WorkerType.GENERAL`` task — the graph never halts.

Reference
---------
- ``06-langgraph-orchestration/app/agents/planner.py`` — Furkan's planner uses a
  similar one-shot decomposition prompt + structured output.
- ``05-DEEP_RESEARCH_AGENT/server/openai_agents/research_planner.py`` — DRA's planner
  emits a research plan with sub-questions; we adapt the shape to per-source tasks.

Sample
------
>>> # plan = decompose("compare GraphRAG and HippoRAG using papers and github", max_workers=4)
>>> # plan.tasks[0].worker_type == WorkerType.PAPER
"""

from __future__ import annotations

from agent.schemas import OrchestrationPlan, WorkerType
from agent.structured_llm import parse_or_raise

_SYSTEM = """\
You are the ORCHESTRATOR of a multi-source RAG agent on the "deep_research" path. The
indexed corpora are:
- research_paper  -> ArXiv-style PDFs (canonical name; legacy alias: "arxiv")
- github          -> README + code chunks
- instagram       -> short captions + threads (community signal, often opinionated)
- knowledge_graph -> NetworkX graph of concepts/relationships extracted from the above

Decompose the user's question into a SHORT list of focused per-source sub-tasks. Each
sub-task targets exactly ONE worker_type and asks for one piece of evidence. The
parallel workers will be merged later by an aggregator.

Allowed worker_type values:
- "paper"     -> retrieve from research_paper corpus
- "github"    -> retrieve from github corpus
- "instagram" -> retrieve from instagram corpus
- "kg"        -> traverse the knowledge graph
- "general"   -> hybrid retrieval across all corpora (use sparingly)

Hard rules:
1. Emit BETWEEN 1 AND 4 tasks. Prefer 2-3.
2. Do NOT spawn duplicate worker_types unless strictly necessary. Prefer DIVERSE
   workers (e.g. paper + github + kg) over three of the same kind.
3. Each task.query should be a self-contained question the worker can answer without
   seeing the others.
4. Each task.objective explains WHY this task helps answer the user's question.
5. Each task.expected_output describes the SHAPE of evidence the worker should return
   (e.g. "concrete benchmark numbers", "code snippets implementing X", "definitions").
6. Set source_filter ONLY when the worker_type already implies that source AND a
   tighter filter helps; otherwise leave it null.
7. task_id values must be short, lowercase, unique, and deterministic-looking
   (e.g. "t1", "t2", "t3"). The node layer may renumber them; do not rely on them.

Also fill:
- summary: a one-sentence restatement of the user's question.
- decomposition_rationale: one or two sentences explaining your task split.
"""


def _user_prompt(query: str, max_workers: int) -> str:
    return (
        f"USER QUESTION:\n{query}\n\n"
        f"MAX_WORKERS: {max_workers}\n\n"
        "Return the orchestration plan."
    )


def decompose(
    query: str,
    *,
    max_workers: int = 4,
    trace_id: str | None = None,
) -> OrchestrationPlan:
    """Run the orchestrator LLM call and return a validated :class:`OrchestrationPlan`.

    The caller (``agent.nodes.orchestrate``) is responsible for capping ``tasks`` to
    ``max_workers`` and for synthesizing a fallback ``GENERAL`` task if the LLM
    returns zero tasks.
    """
    plan = parse_or_raise(
        OrchestrationPlan,
        system_prompt=_SYSTEM,
        user_prompt=_user_prompt(query, max_workers),
        stage="orchestrator",
        trace_id=trace_id,
        temperature=0.0,
        max_tokens=900,
    )
    # Trim to max_workers to enforce the safety cap even if the LLM ignored it.
    if len(plan.tasks) > max_workers:
        plan = OrchestrationPlan(
            summary=plan.summary,
            decomposition_rationale=plan.decomposition_rationale,
            tasks=plan.tasks[:max_workers],
        )
    # Filter out any task whose worker_type is not in the allowed enum (defensive —
    # Pydantic already enforces this; this is a paranoia guard for future enum
    # additions that may slip past the prompt).
    allowed = {wt.value for wt in WorkerType}
    plan = OrchestrationPlan(
        summary=plan.summary,
        decomposition_rationale=plan.decomposition_rationale,
        tasks=[t for t in plan.tasks if t.worker_type.value in allowed],
    )
    return plan


__all__ = ["decompose"]
